### ISSUE TITLE
Αναζήτηση

### ISSUE THREAD

**Issue by escloco** [HaruTzuki/SmartCooking#3]
Κάνει αναζήτηση με το πρώτο υλικό μόνο.
Πρώτη αναζητηση με 1)μπέικον και 2) κοτόπουλο
![image](https://user-images.githubusercontent.com/75433495/102493338-b2367300-407b-11eb-90ad-bed4d58fed5c.png)

Δευτερη αναζήτηση με 1) Κοτόπουλο και 2) Μπεικον
![image](https://user-images.githubusercontent.com/75433495/102493548-06d9ee00-407c-11eb-86c7-e248d8dd740c.png)

Και επίσης νομίζω δε βγάζει σωστά τα "είδη που βρέθηκαν." Τον αριθμό εννοώ.

**Comment by HaruTzuki** [comment]
Το πρόβλημα λύθηκε. Υπήρχε Bug στο πως έδινε η JS στην ASP το QueryString
